### ISSUE TITLE
`add_field` - nested fields when parent key does not exist

### ISSUE THREAD

**Issue by zalmane** [datayoga-io/datayoga#281]
```
steps:
- uses: add_field
  with:
      field: location.street
      language: sql
      expression: lname
```

generates unexpected output:
```
[
  {
    "fname": "jane",
    "lname": "smith",
    "country_code": 1,
    "country_name": "usa",
    "credit_card": "1234-5678-0000-9999",
    "gender": "F",
    "location": {},
    "street": "smith"
  }
]
```
