### ISSUE TITLE
change JMESPath's concat implementation in README and test

### ISSUE THREAD

**Issue by spicy-sauce** [datayoga-io/datayoga#37]
Currently this is the example we have:
```
  - uses: add_field
    with:
      field: full_name
      language: jmespath
      expression: '{ "fname": fname, "lname": lname} | join('' '', values(@))'
```

We have the `concat` block for this purpose, so we probably replace this example with something more intuitive.
