### ISSUE TITLE
`add_field`, `remove_field`, `rename_field` blocks - support list

### ISSUE THREAD

**Issue by spicy-sauce** [datayoga-io/datayoga#43]
Instead of defining multiple blocks for adding new fields, for example, support this format too (list)
```
  - uses: add_field
    with:
      - field: BillingHouseNumber
        expression: split(`BillingAddress`,'.')[0]
      - field: BillingStreet
        expression: split(`BillingAddress`,'.')[1]
      - field: BillingCountry
        expression: upper(`BillingCountry`)
      - field: VAT
        expression: total * 1.17
        language: sql
```

The other format should be also supported for dealing with only one field:
```
  - uses: add_field
    with:
        field: BillingHouseNumber
        expression: split(`BillingAddress`,'.')[0]
```
